# Generate C that implements mp_wasm_trust_load_builtin() from DER CA files.
# Roots are zlib-compressed in ROM; runtime inflates lazily via mp_wasm_trust_add_blob.
#
#   python3 tools/wasmmod.py embed-ca -o build/wasm_trust_ca.c root.crt.der […]
#   # or: tools/wasmmod_embed_ca.py …
#
# Make: MICROPY_WASM_TRUST_CA="a.der b.der"

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import zlib
except ImportError:  # pragma: no cover
    zlib = None  # type: ignore


def c_bytes(data: bytes, name: str) -> str:
    lines = [f"static const uint8_t {name}[] = {{"]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def pack_root(raw: bytes, *, compress: bool) -> tuple[bytes, int, int]:
    """Return (payload, uncompressed_len, stored_len). payload is zlib or raw."""
    if compress and zlib is not None:
        z = zlib.compress(raw, 9)
        # Only keep zlib if it actually shrinks (certs are small; still usually wins).
        if len(z) < len(raw):
            return z, len(raw), len(z)
    return raw, len(raw), len(raw)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--output", type=Path, required=True)
    ap.add_argument(
        "--raw",
        action="store_true",
        help="store uncompressed DER (default: zlib when smaller)",
    )
    ap.add_argument("ders", nargs="+", type=Path, help="root CA DER file(s)")
    args = ap.parse_args()

    entries: list[tuple[str, bytes, int, int]] = []
    for i, path in enumerate(args.ders):
        if not path.is_file():
            print(f"missing {path}", file=sys.stderr)
            return 1
        raw = path.read_bytes()
        if not raw:
            print(f"empty {path}", file=sys.stderr)
            return 1
        payload, ulen, slen = pack_root(raw, compress=not args.raw)
        entries.append((f"mp_wasm_trust_ca_{i}", payload, ulen, slen))
        print(f"  {path.name}: {ulen} -> {slen} bytes", file=sys.stderr)

    parts = [
        "/* Auto-generated by tools/wasmmod_embed_ca.py — do not edit. */",
        "#include <stddef.h>",
        "#include <stdint.h>",
        '#include "extmod/wasmmod/verify.h"',
        "",
        "typedef struct {",
        "    const uint8_t *data;",
        "    uint32_t data_len;",
        "    uint32_t uncompressed_len;",
        "} mp_wasm_trust_ca_entry_t;",
        "",
    ]
    for name, payload, _ulen, _slen in entries:
        parts.append(c_bytes(payload, name))
        parts.append("")

    parts.append(
        f"static const mp_wasm_trust_ca_entry_t mp_wasm_trust_ca_table[{len(entries)}] = {{"
    )
    for name, _payload, ulen, slen in entries:
        parts.append(f"    {{ {name}, {slen}u, {ulen}u }},")
    parts.append("};")
    parts.append("")
    parts.append("void mp_wasm_trust_load_builtin(void) {")
    parts.append(f"    for (size_t i = 0; i < {len(entries)}u; ++i) {{")
    parts.append("        const mp_wasm_trust_ca_entry_t *e = &mp_wasm_trust_ca_table[i];")
    parts.append("        (void)mp_wasm_trust_add_blob(e->data, e->data_len, e->uncompressed_len);")
    parts.append("    }")
    parts.append("}")
    parts.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(parts))
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
